### ISSUE TITLE
能提供详细一点的使用文档和教程吗？Thanks！

### ISSUE THREAD

**Issue by Lam1360** [InternLM/InternLM-WQX#3]

**Comment by gaoyang07** [comment]
hello，InternLM-WQX系列模型的用法跟InternLM团队之前推出的一系列模型相同，您只需要在HuggingFace or ModelScope下载对应ckpt，用transformers等代码加载即可，下面是一个使用transformers框架加载模型并做考试题目的简单示例：
```python
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("internlm/internlm2-wqx-20b", trust_remote_code=True)
# `torch_dtype=torch.float16` 可以令模型以 float16 精度加载，否则 transformers 会将模型加载为 float32，有可能导致显存不足
model = AutoModelForCausalLM.from_pretrained("internlm/internlm2-20b", torch_dtype=torch.float16, trust_remote_code=True).cuda()
model = model.eval()
inputs = tokenizer(["依次填入下列各句横线处的成语，最恰当的一组是（ 　　） \n①医疗质量是关系到病人生命安危的大事，救死扶伤是医务人员        的天职。  \n②中国传统的严父慈母型的家庭关系，常令父亲们        地承担起教育子女的\n义务。  \n③在全国比赛中屡获金奖的我省杂技团，        地承担了这次出国演出任务。  \nA．当仁不让  责无旁贷  义不容辞   \nB．责无旁贷  义不容辞  当仁不让   \nC．义不容辞  责无旁贷  当仁不让   \nD．义不容辞  当仁不让  责无旁贷\n"], return_tensors="pt")
for k,v in inputs.items():
    inputs[k] = v.cuda()
gen_kwargs = {"max_length": 128, "top_p": 0.8, "temperature": 0.8, "do_sample": True, "repetition_penalty": 1.0}
output = model.generate(**inputs, **gen_kwargs)
output = tokenizer.decode(output[0].tolist(), skip_special_tokens=True)
print(output)
```

**Comment by VXenomac** [comment]
```
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM
tokenizer = AutoTokenizer.from_pretrained("internlm/internlm2-wqx-vl-20b", trust_remote_code=True)
# `torch_dtype=torch.float16` 可以令模型以 float16 精度加载，否则 transformers 会将模型加载为 float32，有可能导致显存不足
model = AutoModelForCausalLM.from_pretrained("internlm/internlm2-wqx-vl-20b", torch_dtype=torch.float16, trust_remote_code=True).cuda()
model = model.eval()
```

OSError: Incorrect path_or_model_id: 'internlm/internlm2-wqx-vl-20b/clip_l_560_pro7b'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

**Comment by tianyilt** [comment]
> ```
> import torch
> from transformers import AutoTokenizer, AutoModelForCausalLM
> tokenizer = AutoTokenizer.from_pretrained("internlm/internlm2-wqx-vl-20b", trust_remote_code=True)
> # `torch_dtype=torch.float16` 可以令模型以 float16 精度加载，否则 transformers 会将模型加载为 float32，有可能导致显存不足
> model = AutoModelForCausalLM.from_pretrained("internlm/internlm2-wqx-vl-20b", torch_dtype=torch.float16, trust_remote_code=True).cuda()
> model = model.eval()
> ```
> 
> OSError: Incorrect path_or_model_id: 'internlm/internlm2-wqx-vl-20b/clip_l_560_pro7b'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

Hello，这个问题在于vision_tower的路径没有被正确设置，为了解决这个问题，推荐使用huggingface-cli下载到本地
```
huggingface-cli download internlm/internlm2-wqx-vl-20b --cache-dir path-to-cache
```
然后用以下方式加载模型
```python
import os
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM


device = torch.device("cuda")

model_path = "path-to-cache/path-to-model"
gen_kwargs = {"max_length": 8192, "do_sample": False,"temperature":0.0}
model_name = "InternLM2 WQX VL"
tokenizer = AutoTokenizer.from_pretrained(
    model_path, trust_remote_code=True,
)
model = AutoModelForCausalLM.from_pretrained(
    model_path,
    trust_remote_code=True,
    torch_dtype=torch.float16,
).eval().to(device)
model.tokenizer = tokenizer
```

另一种方式是将vision_tower的`clip_l_560_pro7b`改成绝对路径，方法是找到`path-to-model_dir/build_mlp.py`，找到以下函数
```
def build_vision_tower(path):
    vision_tower = os.path.join(path, 'clip_l_560_pro7b')
    return CLIPVisionTower(vision_tower)
```
将`os.path.join(path, 'clip_l_560_pro7b')`替换为目前clip_l_560_pro7b文件夹的绝对路径`path-to-model_dir/clip_l_560_pro7b`。

更具体的使用方式请关注近期将会更新的[GAOKAO-Eval](https://github.com/open-compass/GAOKAO-Eval)多模态考题推理时候发布的ipynb和脚本。

**Comment by tianyilt** [comment]
> ```
> import torch
> from transformers import AutoTokenizer, AutoModelForCausalLM
> tokenizer = AutoTokenizer.from_pretrained("internlm/internlm2-wqx-vl-20b", trust_remote_code=True)
> # `torch_dtype=torch.float16` 可以令模型以 float16 精度加载，否则 transformers 会将模型加载为 float32，有可能导致显存不足
> model = AutoModelForCausalLM.from_pretrained("internlm/internlm2-wqx-vl-20b", torch_dtype=torch.float16, trust_remote_code=True).cuda()
> model = model.eval()
> ```
> 
> OSError: Incorrect path_or_model_id: 'internlm/internlm2-wqx-vl-20b/clip_l_560_pro7b'. Please provide either the path to a local folder or the repo_id of a model on the Hub.

您好，这个问题在今天的更新中被修复了，可以直接通过url进行load了。

**Comment by tianyilt** [comment]
感谢大家关注这个模型，目前文档已经更新quick start部分来快速测试，另外欢迎大家访问[GAOKAO-Eval](https://github.com/open-compass/GAOKAO-Eval)来评估包括文曲星在内不同模型在高考环境中的表现。
